path: data # dataset root dir
train: images/train
val: val/train

model_version: data/model_YOLO_seg/yolov8x-seg.pt

# Class
names:
    0: target_plant

masks:
    train: data/YOLO_dataset/masks/train
    val: data/YOLO_dataset/masks/val

image_size: 640
batch_size: 16
epochs: 100
model_format: "PyTorch"