path: /home/nsingh27/AgIR-FieldSegmentation/data/YOLO_dataset # dataset root dir
train: /home/nsingh27/AgIR-FieldSegmentation/data/YOLO_dataset/images/train
val: /home/nsingh27/AgIR-FieldSegmentation/data/YOLO_dataset/images/val

model_version: /home/nsingh27/AgIR-FieldSegmentation/data/model_YOLO_seg/yolov8x-seg.pt

# Class
names:
    0: target_plant

masks:
    train: /home/nsingh27/AgIR-FieldSegmentation/data/YOLO_dataset/masks/train
    val: /home/nsingh27/AgIR-FieldSegmentation/data/YOLO_dataset/masks/val

image_size: 640
batch_size: 16
epochs: 100
model_format: "PyTorch"